services:
  model-inference:
    container_name: model-inference
    privileged: true
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    build:
      context: ./
      dockerfile: ./dockerfile
      network: host
