name: Repo-Workflow

on:
  pull_request:
    branches:
      - 'main'
    types: [synchronize, reopened, closed, opened]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  ReceiveVideoWorkflow:
    uses: ./.github/workflows/receive_video_workflow.yaml

  ModelInferenceWorkflow:
    uses: ./.github/workflows/model_inference_workflow.yaml

  workflow-success:
    runs-on: ubuntu-latest
    needs:
      - ReceiveVideoWorkflow
      - ModelInferenceWorkflow
    if: always()
    steps:
    - name: Check Statuses
      run: |
        if [[ "${{ github.event.pull_request.draft }}" != 'false' ]]; then
          echo "switching from draft can cause an erroneous pass of the actions. Push a new commit or reopen."
          exit 1
        fi
        for result in \
          ${{ needs.ModelInferenceWorkflow.result }} \
          ${{ needs.ReceiveVideoWorkflow.result }}

          do 
            if [[ $result != "success" && $result != "skipped" ]]; then
              exit 1
            fi
          done
